# print("Hello,World!")
Name = input("Introduce-ti numele dumneavoastra:")
height = input('introduce-ti inaltimea dumneavoastra')
weight= input('introduce=ti greutatea dumneavoastra')
print("Buna ziua " + Name)
print("Aveti inaltimea de:"+ height +" si greutatea de:" +weight)
